# Generated by Django 5.2.6 on 2026-02-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_startup_is_deck_builder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='confidence_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='data_source_confidence',
            field=models.CharField(default='Low', max_length=50),
        ),
    ]
